#!/bin/sh
set -e
APP_DOCKER_DIR=/var/www/html
HOST_OSTYPE=${HOST_OSTYPE-linux}
APP_DOCROOT=web
PRIVATE_DIR=${PRIVATE_DIR-sites/default/files/private}


# When volume mounted on a Mac some permissions commands are different.
# If it's not volume mounted then Docker for Mac uses the Linux set of permissions.
if echo $HOST_OSTYPE | grep darwin; then
  HOST_OSTYPE=darwin
fi

# Make directory if it doesn't exist
mkdir -p "$APP_DOCKER_DIR/$APP_DOCROOT/sites/default/files"

if [ "$HOST_OSTYPE" != "darwin" ]; then
  chown -R root:www-data "$APP_DOCKER_DIR"
  chmod -R 0640 "$APP_DOCKER_DIR"
else
  chmod -R o-rwx "$APP_DOCKER_DIR"
  chmod -R g-wx "$APP_DOCKER_DIR"
  chmod -R u+rw "$APP_DOCKER_DIR"
fi

  chmod -R ug+X "$APP_DOCKER_DIR"
  chmod -R g+w "$APP_DOCKER_DIR/$APP_DOCROOT/sites/default/files"
  find "$APP_DOCKER_DIR/$APP_DOCROOT/sites/default/files" -type d -print0 | xargs -0 chmod g+s

  # Make drush executable
  chmod ugo+x $APP_DOCKER_DIR/vendor/drush/drush/drush.launcher || echo "drush.launcher not found"
  chmod u+x $APP_DOCKER_DIR/vendor/drush/drush/drush || echo "Drush not found"
  chmod u+x $APP_DOCKER_DIR/vendor/bin/* || echo "vendor/bin not found"




if [ -d "$APP_DOCKER_DIR/$APP_DOCROOT/$PRIVATE_DIR" ]; then
  chmod -R g+w "$APP_DOCKER_DIR/$APP_DOCROOT/$PRIVATE_DIR"
  find "$APP_DOCKER_DIR/$APP_DOCROOT/$PRIVATE_DIR" -type d -print0 | xargs -0 chmod g+s
else
  echo "No private directory found"
fi
